### ISSUE TITLE
gunicorn 

### ISSUE THREAD

**Issue by hans-lammda** [Nordix/bomres#34]
I noticed that Nordix have gunicorn , therefore I did not integrate uwsgi. 
Lets discuss which server to use , until then add both servers.

**Comment by tsaarni** [comment]
Hi @hans-lammda, I am working with some TLS improvements in Gunicorn and needed a fork for that work - that is why we have it under Nordix.

**Comment by hans-lammda** [comment]
In our Kubernetes deployment TLS will be terminated by the ingress-controller, However Gunicorn seems to be a good choice with support for async services.

**Comment by tsaarni** [comment]
Yep, it is. In our case, we use TLS for the internal leg of the connection too, from proxy to the backend services. The Nordix fork has finer control for TLS options e.g. for enforcing TLS 1.3, which hopefully gets accepted in upstream at some point.
